version: '3.4'

services:
  main-bot:
    depends_on:
      - worker
    build: main-bot
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REDIS_HOST=${REDIS_HOST}
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis.config:/redis.conf
    command: ['redis-server', '/redis.conf']
  worker:
    depends_on:
      - redis
    build: worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - FIXER_KEY=${FIXER_KEY}
  stream-bot:
    depends_on:
      - redis
    build: stream-bot
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REDIS_HOST=${REDIS_HOST}
