version: '3.4'

services:
  main-bot:
    depends_on:
      - worker
    build: main-bot
    restart: always
    volumes:
      - ./emoji_dict.py:/usr/src/main-bot/emoji_dict.py
      - ./acronym_dict.py:/usr/src/main-bot/acronym_dict.py
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PW=${REDIS_PW}
      - TZ=${TZ}
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=${TZ}
      - REDIS_PW=${REDIS_PW}
    command: redis-server --bind redis --requirepass ${REDIS_PW} --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
  worker:
    depends_on:
      - redis
    build: worker
    restart: always
    volumes:
      - ./emoji_dict.py:/usr/src/worker/emoji_dict.py
      - ./acronym_dict.py:/usr/src/worker/acronym_dict.py
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - FIXER_KEY=${FIXER_KEY}
      - REDIS_PW=${REDIS_PW}
      - TZ=${TZ}
  stream-bot:
    depends_on:
      - redis
    build: stream-bot
    restart: always
    volumes:
      - ./emoji_dict.py:/usr/src/stream-bot/emoji_dict.py
      - ./acronym_dict.py:/usr/src/stream-bot/acronym_dict.py
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PW=${REDIS_PW}
      - TZ=${TZ}
